server:
   port: 8081
   read_timeout: 5s
   write_timeout: 5s
database:
  dsn: "postgres://user:password@localhost:5432/eventdb_test?sslmode=disable"
  #dsn: "postgres://user:password@postgres-test.int-tests.orb.local:5432/eventdb_test?sslmode=disable"
redis:
  addr: "localhost:6380" # Адрес деплой
  # addr: "rredis-test.int-tests.orb.local:6380" #Адрес для мака
  password: ""
  rdb: 0
 # Таймауты
  dial_timeout: 5      # 5s на установку соединения
  read_timeout: 3      # 3s на чтение ответа
  write_timeout: 3     # 3s на отправку команды
  pool_timeout: 1      # 1s на ожидание свободного соединения
  # Retry настройки
  max_retries: 3       # 3 попытки при ошибках
  min_retry_backoff: 1 # Минимальная задержка 1s
  max_retry_backoff: 5 # Максимальная задержка 5s
  # Пул соединений
  pool_size: 20        # Максимум 20 одновременных соединений
  min_idle_conns: 5    # Всегда 5 готовых соединений
  # Время жизни соединений
  conn_max_idle_time: 300  # 5 минут простоя
  conn_max_lifetime: 3600  # 1 час максимальной жизни
