version: "3.9"

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: eventdb-test
    restart: unless-stopped
    environment:
      - POSTGRES_DB=eventdb_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"  
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d eventdb_test"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis-test:
      image: redis:7.2-alpine
      container_name: eventredis-test
      restart: unless-stopped
      ports:
        - "6380:6379"
      volumes:
        - redisdata-test:/data
      command: redis-server --save 60 1 --loglevel warning
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5

volumes:
  pgdata-test:
  redisdata-test: